services:
  - type: web
    name: key-system-api
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: node dist/server/index.js
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false